# Generated by Django 3.1.5 on 2021-01-25 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_app', '0005_auto_20210125_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='opg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='OPG_app.opg'),
        ),
    ]
