# Generated by Django 3.1.5 on 2021-01-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_app', '0006_auto_20210125_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OPG_app.opg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='opg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OPG_app.opg'),
        ),
    ]
